//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventana1.Entiti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KDBEntities : DbContext
    {
        public KDBEntities()
            : base("name=KDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KDM1> KDM1 { get; set; }
        public virtual DbSet<KDM1COMEN> KDM1COMEN { get; set; }
        public virtual DbSet<KDMENT> KDMENT { get; set; }
        public virtual DbSet<KDUD> KDUD { get; set; }
        public virtual DbSet<KDUDA> KDUDA { get; set; }
    
        public virtual ObjectResult<string> NumeroMAX(string dATO, string tIPO)
        {
            var dATOParameter = dATO != null ?
                new ObjectParameter("DATO", dATO) :
                new ObjectParameter("DATO", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("NumeroMAX", dATOParameter, tIPOParameter);
        }
    }
}
