//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negocios.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; style=&quot;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta content=&quot;width=device-width, initial-scale=1&quot; name=&quot;viewport&quot;&gt;
        ///  &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content= [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Arnian2022 {
            get {
                return ResourceManager.GetString("Arnian2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///&lt;body&gt;
        ///	&lt;center&gt;
        ///		&lt;table style=&quot;font-family: sans-serif; width:100%; border: 1px solid #333;&quot;&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;
        ///					&lt;table style=&quot;width: 100%&quot;&gt;
        ///						&lt;tr style=&quot;background: #344fb6;&quot;&gt;
        ///							&lt;td style=&quot;width: 100%; height: 40px;&quot;&gt;
        ///								&lt;p style=&quot;color: #fff; font-size:26px; text-align: center;&quot;&gt; Orden de Entrada &lt;/p&gt;
        ///							&lt;/td&gt;
        ///							&lt;td style=&quot;width: 30%;&quot;&gt;
        ///						&lt;/tr&gt;
        ///					&lt;/table&gt;
        ///					&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;
        ///					&lt;table style=&quot;width: 100%;&quot;&gt;
        ///						&lt;tr&gt;
        ///							&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string correoskepler {
            get {
                return ResourceManager.GetString("correoskepler", resourceCulture);
            }
        }
    }
}
