//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    
    public partial class DatosCXC_Result1
    {
        public string Entrada { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public string SucursalOrigen { get; set; }
        public string Cotizacion { get; set; }
        public string Cliente { get; set; }
        public string Alias { get; set; }
        public string Cordinador { get; set; }
        public Nullable<decimal> ValorFactura { get; set; }
        public Nullable<decimal> ValorArnian { get; set; }
        public Nullable<decimal> ValorArnian1 { get; set; }
        public string BOL { get; set; }
        public string Carga { get; set; }
        public string Salida { get; set; }
        public string Estatus { get; set; }
        public string EstatusPago { get; set; }
        public string Comentario { get; set; }
    }
}
