//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    
    public partial class Docto_Prv_Result1
    {
        public string Column1 { get; set; }
        public string C10 { get; set; }
        public Nullable<System.DateTime> C9 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public string C7 { get; set; }
        public string C11 { get; set; }
        public string Column2 { get; set; }
        public string C93 { get; set; }
        public string C94 { get; set; }
        public string C95 { get; set; }
        public string C96 { get; set; }
        public Nullable<decimal> C97 { get; set; }
        public string C98 { get; set; }
        public Nullable<decimal> C106 { get; set; }
        public string C100 { get; set; }
        public string C101 { get; set; }
        public string C102 { get; set; }
        public string C103 { get; set; }
        public string C1 { get; set; }
        public Nullable<decimal> c1061 { get; set; }
        public string c12 { get; set; }
    }
}
