//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSBARCODE
    {
        public int id { get; set; }
        public string C1 { get; set; }
        public string C6 { get; set; }
        public string C9 { get; set; }
        public byte[] BARCODE { get; set; }
        public string E1 { get; set; }
        public string E2 { get; set; }
    }
}
