//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSROL_OPER
    {
        public int Id { get; set; }
        public int IdRol { get; set; }
        public int IdOperacion { get; set; }
    
        public virtual DSOPERACION DSOPERACION { get; set; }
        public virtual DSROL2 DSROL2 { get; set; }
    }
}
