//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSUSER
    {
        public int IdUsuario { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Numero { get; set; }
        public int IdRol { get; set; }
        public string Activo { get; set; }
        public string ExtraA { get; set; }
        public string ExtraB { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual DSROL2 DSROL2 { get; set; }
    }
}
