//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMovimientos
    {
        public int MovimientoID { get; set; }
        public int Folio { get; set; }
        public int TipoFolio { get; set; }
        public string Etiqueta { get; set; }
        public int CodigoTipoMovimiento { get; set; }
        public string DocumentoAnterior { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> FechaHoraMovimiento { get; set; }
        public string UsuarioResponsable { get; set; }
        public string Coordinador { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public string IP { get; set; }
        public string DescripcionCorta { get; set; }
        public string LinkDocumento { get; set; }
        public string Alias { get; set; }
        public string Cotizacion { get; set; }
        public Nullable<decimal> ValorArnian { get; set; }
        public Nullable<decimal> ValorFactura { get; set; }
        public string TrackingProveedor { get; set; }
        public Nullable<bool> Entrada { get; set; }
    }
}
