//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IDInventario { get; set; }
        public Nullable<System.DateTime> FechaInicioInventario { get; set; }
        public Nullable<System.DateTime> FechaFinalInventario { get; set; }
        public string IDBodega { get; set; }
        public string RealizadoPor { get; set; }
        public string SeccionInventario { get; set; }
        public string TipoInventario { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> CantidadContada { get; set; }
        public string IDResponsableVerificacion { get; set; }
        public Nullable<int> IDEstado { get; set; }
    
        public virtual EstadosAlmacenamiento EstadosAlmacenamiento { get; set; }
    }
}
