//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDM1
    {
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public decimal C4 { get; set; }
        public decimal C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<System.DateTime> C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public string C17 { get; set; }
        public Nullable<System.DateTime> C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public Nullable<decimal> C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public Nullable<decimal> C28 { get; set; }
        public Nullable<decimal> C29 { get; set; }
        public string C30 { get; set; }
        public string C31 { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
        public string C34 { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public Nullable<decimal> C37 { get; set; }
        public Nullable<decimal> C38 { get; set; }
        public string C39 { get; set; }
        public Nullable<double> C40 { get; set; }
        public Nullable<System.DateTime> C41 { get; set; }
        public Nullable<decimal> C42 { get; set; }
        public string C43 { get; set; }
        public string C44 { get; set; }
        public string C45 { get; set; }
        public string C46 { get; set; }
        public string C47 { get; set; }
        public string C48 { get; set; }
        public Nullable<decimal> C49 { get; set; }
        public Nullable<double> C50 { get; set; }
        public Nullable<double> C51 { get; set; }
        public Nullable<double> C52 { get; set; }
        public Nullable<double> C53 { get; set; }
        public Nullable<double> C54 { get; set; }
        public Nullable<double> C55 { get; set; }
        public Nullable<double> C56 { get; set; }
        public Nullable<double> C57 { get; set; }
        public Nullable<double> C58 { get; set; }
        public Nullable<double> C59 { get; set; }
        public Nullable<double> C60 { get; set; }
        public string C61 { get; set; }
        public string C62 { get; set; }
        public string C63 { get; set; }
        public string C64 { get; set; }
        public Nullable<decimal> C65 { get; set; }
        public string C66 { get; set; }
        public string C67 { get; set; }
        public Nullable<System.DateTime> C68 { get; set; }
        public string C69 { get; set; }
        public string C70 { get; set; }
        public string C71 { get; set; }
        public string C72 { get; set; }
        public string C73 { get; set; }
        public string C74 { get; set; }
        public string C75 { get; set; }
        public string C76 { get; set; }
        public string C77 { get; set; }
        public string C78 { get; set; }
        public string C79 { get; set; }
        public string C80 { get; set; }
        public string C81 { get; set; }
        public string C82 { get; set; }
        public string C83 { get; set; }
        public string C84 { get; set; }
        public string C85 { get; set; }
        public string C86 { get; set; }
        public string C87 { get; set; }
        public string C88 { get; set; }
        public string C89 { get; set; }
        public string C90 { get; set; }
        public Nullable<System.DateTime> C91 { get; set; }
        public string C92 { get; set; }
        public string C93 { get; set; }
        public string C94 { get; set; }
        public string C95 { get; set; }
        public string C96 { get; set; }
        public Nullable<decimal> C97 { get; set; }
        public string C98 { get; set; }
        public Nullable<decimal> C99 { get; set; }
        public string C100 { get; set; }
        public string C101 { get; set; }
        public string C102 { get; set; }
        public string C103 { get; set; }
        public Nullable<decimal> C104 { get; set; }
        public Nullable<decimal> C105 { get; set; }
        public Nullable<decimal> C106 { get; set; }
        public string C107 { get; set; }
        public string C108 { get; set; }
        public string C109 { get; set; }
        public string C110 { get; set; }
        public Nullable<System.DateTime> C111 { get; set; }
        public string C112 { get; set; }
        public string C113 { get; set; }
        public string C114 { get; set; }
        public string C115 { get; set; }
    }
}
