//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDM2
    {
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public decimal C4 { get; set; }
        public decimal C5 { get; set; }
        public string C6 { get; set; }
        public decimal C7 { get; set; }
        public string C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<double> C14 { get; set; }
        public Nullable<double> C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public string C17 { get; set; }
        public Nullable<double> C18 { get; set; }
        public string C19 { get; set; }
        public Nullable<decimal> C20 { get; set; }
        public Nullable<decimal> C21 { get; set; }
        public string C22 { get; set; }
        public Nullable<decimal> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public string C25 { get; set; }
        public Nullable<double> C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public Nullable<decimal> C29 { get; set; }
        public Nullable<decimal> C30 { get; set; }
        public Nullable<double> C31 { get; set; }
        public Nullable<System.DateTime> C32 { get; set; }
        public Nullable<decimal> C33 { get; set; }
        public Nullable<decimal> C34 { get; set; }
        public Nullable<decimal> C35 { get; set; }
        public string C36 { get; set; }
        public Nullable<decimal> C37 { get; set; }
        public Nullable<decimal> C38 { get; set; }
        public string C39 { get; set; }
        public string C40 { get; set; }
    }
}
