//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDMENT
    {
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public decimal C4 { get; set; }
        public decimal C5 { get; set; }
        public string C6 { get; set; }
        public decimal C7 { get; set; }
        public string C8 { get; set; }
        public string C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public Nullable<System.DateTime> C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public string C29 { get; set; }
        public string C30 { get; set; }
        public string C31 { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
        public string C34 { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public string C37 { get; set; }
        public Nullable<decimal> C38 { get; set; }
        public Nullable<decimal> C39 { get; set; }
        public Nullable<decimal> C40 { get; set; }
        public string C41 { get; set; }
        public string C42 { get; set; }
        public string C43 { get; set; }
        public string C44 { get; set; }
        public string C45 { get; set; }
        public string C46 { get; set; }
        public Nullable<decimal> C47 { get; set; }
        public Nullable<decimal> C48 { get; set; }
        public string C49 { get; set; }
        public Nullable<decimal> C50 { get; set; }
        public Nullable<decimal> C51 { get; set; }
        public string C52 { get; set; }
        public string C53 { get; set; }
        public string C54 { get; set; }
        public string C55 { get; set; }
        public string C56 { get; set; }
        public string C57 { get; set; }
        public string C58 { get; set; }
        public string C59 { get; set; }
        public string C60 { get; set; }
        public string C61 { get; set; }
        public string C62 { get; set; }
        public string C63 { get; set; }
        public string C64 { get; set; }
        public string C65 { get; set; }
        public string C66 { get; set; }
        public string C67 { get; set; }
        public string C68 { get; set; }
        public string C69 { get; set; }
        public string C70 { get; set; }
        public string C71 { get; set; }
        public string C72 { get; set; }
        public string C73 { get; set; }
        public string C74 { get; set; }
        public string C75 { get; set; }
        public string C76 { get; set; }
        public string C77 { get; set; }
        public string C78 { get; set; }
        public string C79 { get; set; }
        public string C80 { get; set; }
        public string C81 { get; set; }
        public Nullable<int> IDinventario { get; set; }
        public Nullable<long> odooidproduct { get; set; }
        public string odoosalesp { get; set; }
    }
}
