//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Datosenti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebasEntities : DbContext
    {
        public PruebasEntities()
            : base("name=PruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KDID> KDID { get; set; }
        public virtual DbSet<KDM1> KDM1 { get; set; }
        public virtual DbSet<KDM1COMEN> KDM1COMEN { get; set; }
        public virtual DbSet<KDMENT> KDMENT { get; set; }
        public virtual DbSet<KDUD> KDUD { get; set; }
        public virtual DbSet<KDUDA> KDUDA { get; set; }
        public virtual DbSet<KDUSUARIOS> KDUSUARIOS { get; set; }
        public virtual DbSet<KDUV> KDUV { get; set; }
        public virtual DbSet<KDMS> KDMS { get; set; }
        public virtual DbSet<KDXD> KDXD { get; set; }
    }
}
